### ISSUE TITLE
How to pass params?

### ISSUE THREAD

**Issue by arivera12** [dhershman1/vue-debounce#1]
I tried this

`v-debounce:1s='test(form.model.name)'`

and I get this error 

`Uncaught TypeError: i is not a function`

**Comment by arivera12** [comment]
I just tried this

`v-debounce:1s='(event) => { test(form.model.name) }'`

no error message its been displayed but nothing its getting fired.

**Comment by dhershman1** [comment]
Hey! So to pass params you'll need to utilize partial application. 

`v-debounce:1s='test(form.model.name)'`

And in your `methods` object:

```js
test (name) {
  return value => {
    // Do some stuff in here
  }
}
```

If your `form.model.name` lives inside your vue data you should also be able to access it through `this.form.model.name`

If you run into more trouble here let me know and maybe we can approach with an alternative solution.

**Comment by dhershman1** [comment]
Also by default whatever you've attached the directive to input wise the value of that input will be sent to your provided function once the debounce triggers.

**Comment by arivera12** [comment]
I am using vuetify for this. What I have inside my method is 
```
test (val) {
  console.log(val)
}
```
But using your approach stills give me the same error.

**Comment by dhershman1** [comment]
Okay so in your test function try this:

```js
test (val) {
  console.log(val)
  return cbVal => {
    console.log('captured', cbVal)
    console.log('param', val)
  }
}
```

I am able to see my original `val` and the `cbVal`

**Comment by arivera12** [comment]
@dhershman1 this was working as expected it just google chrome that was hiding me the info on the console cause I clicked on the errors filter and not to show all the console messages. omg. I am sorry for the waste of your time. :cry:

**Comment by dhershman1** [comment]
Sorry for the super duper late reply to this, but no worries I am just glad we got it working properly! Lol, no time wasted.
