### ISSUE TITLE
Add debounce delay parameter for custom debounces

### ISSUE THREAD

**Issue by tripflex** [dhershman1/vue-debounce#11]
Thanks for creating this lib, i was going to make one myself if i couldn't find one and this is perfect!

In my specific situation though, the user has the ability to configure the debounce delay for each field itself ... would be good to have a prop that we could pass to define the debounce delay (somehow).  I know it's possible to define it at a global level with a dynamic value, but what about on a per input basis?

**Comment by tripflex** [comment]
Disregard, this should be possible using dynamic directive arguments

https://vuejs.org/v2/guide/custom-directive.html#Dynamic-Directive-Arguments

**Comment by dhershman1** [comment]
Nice find! Let me know how this works out for you in your situation.

**Comment by tripflex** [comment]
@dhershman1 thanks for quick response, it works perfectly no issues at all!

example:

```
<input type="text" v-debounce[delay]="updateValue" />
data(){
    return {
        delay: 500
    }
}
```
