### ISSUE TITLE
trigger on Enter key only

### ISSUE THREAD

**Issue by pecholleyc** [dhershman1/vue-debounce#16]
Couldn't find a way to call the debounce function by pressing only the Enter Key (normal input behavior)
Basically what I would like to do is to remove the default event 'keyup' and get back the normal behavior of my input:

` v-debounce:500="search"  debounce-events=""`

or to restrict it to only the Enter key (similar to the Key Modifiers of Vue)

` v-debounce:500="search"  :debounce-events="'keyup.enter'"`

**Comment by dhershman1** [comment]
I'm not sure I follow, this sounds like you don't need the debounce solution if you don't want it to trigger unless they hit the enter key?

**Comment by pecholleyc** [comment]
I do need the debounce, but since other events can also call the input's search function, I decided simply to import the debounce function, as explain in the Readme, and pass it my search function. Works fine.
