### ISSUE TITLE
Identify Event Fired

### ISSUE THREAD

**Issue by jssouders** [dhershman1/vue-debounce#20]
If you have multiple events configured is it possible to tell which event fired the method?

**Comment by dhershman1** [comment]
You should be getting back the event object upon fire, so you should be able to get it from there. If not could you provide me an example usage your doing? Thank you.

**Comment by jssouders** [comment]
I have included the code snippet below.  I have an input text box that uses vue-debounce to call a method called updateMap.  In the updateMap method the value of the textbox is passed into the function (val), but there are no additional arguments(obj is undefined) that have any event details.
```
 <v-text-field
  v-debounce:1000ms="updateMap"
  debounce-events="['input']"
/>

updateMap (val, obj) {
      console.log(val, obj);
}
```

**Comment by dhershman1** [comment]
Oh I see what you mean. and you're correct there isn't a proper way to test the event as I don't seem to passing it along. Maybe I will change the function so it passes the value as well as the event as a 2nd param.

**Comment by jssouders** [comment]
@dhershman1 Passing the event as the 2nd parameter would be perfect.

**Comment by dhershman1** [comment]
Added with PR #21 

Released under v2.4.0 on npm, if you update you should be good to go. Let me know if you hit any problems ASAP!

**Comment by jssouders** [comment]
@dhershman1 Awesome!  Thanks for the quick turnaround.  Have a good weekend.

**Comment by dhershman1** [comment]
No problem! Thank you for the issue!

You as well.
