### ISSUE TITLE
Overwrite fireOnEmpty on a per element basis

### ISSUE THREAD

**Issue by dwhoop55** [dhershman1/vue-debounce#22]
Is there an option to set fireOnEmpty for an element which overwrites the default fireOnEmpty?
I have a few inputs where the default `fireOnEmpty: true` breaks functionality but some others which should fire when they are cleared with a click and only emit `input, ""`.
Something like this would be wonderful:
`<b-input v-debounce="onSearch" :v-debounce-fire-on-empty="true" />`

Thank you for  vue-debounce, it helped a lot already!

**Comment by dhershman1** [comment]
Can you give me the code example you were messing with?

I will look into a potential option that allows you to do that, similar to how `v-debounce.lock` works. 

This will probably be the best course of action in expanding the functionality.

**Comment by dhershman1** [comment]
There was a bug I just found and addressed with the fireOnEmpty option, but I am going to continue down the route of adding in modifiers as well.

**Comment by dwhoop55** [comment]
I'm using the [input component](https://buefy.org/documentation/input) from [buefy](https://buefy.org/) which fires empty `""` `input` event when clicking the native X for clearing the field:
![native](https://user-images.githubusercontent.com/14042518/75164059-7911c880-5720-11ea-9c2a-fdd7ecd023ce.png)

```
 <b-input
          v-debounce="onSearch"
          v-model="searchString"
          placeholder="Search.."
          type="search"
          icon="magnify">
</b-input>
```

There is an event `icon-right-click` which fires when clicking on the right icon. However, this is not the native clear icon. When setting ```type="search"``` the field will show an X for clearing, this is not the same X that you can set via
```
icon-right="close-circle"
icon-right-clickable
@icon-right-click="clearIconClick"
```
Native and icon 'X':
![native_and_icon](https://user-images.githubusercontent.com/14042518/75164147-9f376880-5720-11ea-9c3d-34bd3f128f7a.png)

I tried to create a small [code playground](https://codepen.io/dwhoop55/pen/MWwJodL) but could not get it to work :)

**Comment by dhershman1** [comment]
Okay so the [development](https://github.com/dhershman1/vue-debounce/tree/development) branch has been updated with some bug fixes as well as the new features of being able to fire on specific inputs when they're empty.

If you don't mind using this branch and trying it out for what you're doing I would greatly appreciate it!

**Comment by dwhoop55** [comment]
Works perfectly, thank you!

Maybe a small hint, for everyone reading this and using buefy:
You need to either append ```input``` to the default ```listenTo: 'keyup',``` event - or add/use it via ```:debounce-events="'input'"```
Without, clicking the X will not work even when you see the ```input``` event being emitted ;)

You can then use fireonempty on the input like so:
```
<b-input
          v-debounce.fireonempty="onSearch"
          type="search"
          icon="magnify"
/>
```
