### ISSUE TITLE
Unclear documentation regarding modifiers

### ISSUE THREAD

**Issue by Amndeep7** [dhershman1/vue-debounce#37]
Documentation makes it seem like you should be using capitals in your modifiers (such as for `fireOnEmpty`), but the code actually expects all lower-case (`fireonempty`).  The example given only shows `lock` which doesn't clarify the situation when all you look at is the documentation.

I think there are three different ways to move forward:

1) Update the documentation to show that the modifiers should only be lowercase.  This would be the least amount of work.  (Wouldn't even need a new release, but otherwise would be a patch increment.)

2) Update the code to accept both lower-case and camelCase modifiers.  This would match what the user would expect regarding the documentation as it stands now but also not break current users; however, it would make the codebase more complicated due to having to check against both forms.  (Would be a minor version increment.)

3) Update the code to match the current documentation.  This would match what the user would expect regarding the documentation but would break current users; however, the codebase wouldn't increase in complexity.  (Would be a major version increment.)

**Comment by dhershman1** [comment]
You're right, I think I even noticed this a little while ago and then forgot because work had picked up. I'll correct the documentation because I think regardless vue always sends lowercase to my plugin, which is why those only seem to work.

**Comment by dhershman1** [comment]
I'll also add examples of using modifiers not just options as I don't know why I didn't do that...

**Comment by dhershman1** [comment]
Do you mind checking the development branch and see if that helps clear things up and makes it less confusing?

**Comment by Amndeep7** [comment]
Can't leave a comment on the code cause you put it in the branch already instead of as a PR.  If you don't wanna change much, I would rewrite

'Using modifiers works just like normal vue directives above you see the `lock` and `unlock` modifiers here is an example of the others:'

to be

'Using modifiers works just like normal Vue directives.  Above you saw the `lock` and `unlock` modifiers in use, here are examples of the rest:'

However, what would be better would be to move the lock/unlock examples down to this section as well.  The block you have them in is 'You can pass the time in multiple formats:', but they don't actually have anything to do with time formats.  Then you could rewrite that explaining sentence to be something like

'Using modifiers works just like normal Vue directives.  You can chain them to the time format and each other.  Some examples include:'

**Comment by dhershman1** [comment]
v2.5.4 released with these changes feel free to reopen if you feel more needs done.
