### ISSUE TITLE
Vue-debounce brakes in IE11

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [dhershman1/vue-debounce#40]
Please, add IE11 support. Once I add vue-debounce to my project I start getting SCRIPT1002: Syntax error that is coming from kyanite@1.3.0 dependency of vue-debounce which is using some syntax that go beyond ES5 IE11 capabilities. I've created a separate issue to reflect the actual cause of the problem here: https://github.com/dhershman1/kyanite/issues/149

**Comment by dhershman1** [comment]
v2.5.6 should address this issue. If not, please re open if needed.

**Comment by dhershman1** [comment]
Oh you know what, I wonder if it's because Kyanite has a module field in the package.json which points to the index.js of src, and thats why webpack is grabbing that.

**Comment by AndrewBogdanovTSS** [comment]
Yes. That is exactly what's happening. Since I used this lib in Nuxt one woraround that I came up with was manually transpiling kyonite lib with the help of Nuxt. But frankly speaking I've stop using this lib in favor of my custom implementation since including the whole Kyanite as a dependency to just perform a simple debounce is a huge overkill. Kyanite is more than 100kbs in size and I think you just use couple of it's functions so I don't see why the whole lib should be included.

**Comment by dhershman1** [comment]
Kyanite is only 17kb, plus its tree shaken by rollup or it should be.

Regardless to many compatibility issues seem to be introduced so v2.5.7 should go back to the built in functions instead of using kyanites.

**Comment by dhershman1** [comment]
Okay @neclimdul v2.5.7 should be back to normal if you want to use that version. Thank you for bringing this to my attention, feel free to open a new issue if your problem persists.

**Comment by AndrewBogdanovTSS** [comment]
@dhershman1  https://take.ms/wq1EJ I always try to analyze the raw size of the dependency since that is what is getting parsed, analyzed and executed by the browser in the end. If you run the lighthouse score you will notice that it's the biggest performance bottleneck for the majority of SPA applications due to the amount of JS code they use, so even if you are using Brotli to serve your assets (which I do) it only means that the js bundle will download faster but not execute faster and on something like Nexus5 with its slow mobile processor - it's much more critical than a bandwidth limitation. Anyway, I saw that in v2.5.7 you've made it dependentless which is great. Thanks, I think I will revisit this library 😄
