### ISSUE TITLE
does this fire immediately upon first use?

### ISSUE THREAD

**Issue by inspire22** [dhershman1/vue-debounce#44]
There's lots of implementations of "debounce" out there - could you clarify if this first the first time immediately, then prevents a second time firing until the debounce has worn off.  Or if there's a configuration option for this.

I was hoping to use this to prevent accidental double-clicking of toggleable buttons in a mobile app.

**Comment by dhershman1** [comment]
No the debounce is in effect from the very first input. So the wait time is triggered even on first interaction.

Instead of using debounce for that maybe instead you could just disable the button on click for a second or so. That might be an easier more lightweight approach!

**Comment by inspire22** [comment]
Sounds good, thank you :)
