### ISSUE TITLE
Failed to resolve directive: debounce #1044 

### ISSUE THREAD

**Issue by kendaniels** [dhershman1/vue-debounce#45]
Trying to use this package with [vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder but can't get it to work.

I've installed the vue-debounce package, and added this to background.js:

```
import Vue from 'vue'
import Vuex from 'vuex'
import vueDebounce from 'vue-debounce'

Vue.use(Vuex, vueDebounce)
```

I assumed that would work, but I get the following error:

`[Vue warn]: Failed to resolve directive: debounce`

After a bit of Googling, I see that there is an option to import the module directly into the component, which I have tried:

```
import { debounce } from 'vue-debounce'
```

and setting the directive up like this:

```
export default {
  directives: {
      debounce
  },
```

which gets rid of the error. But...

My input contains the appropriate syntax: `<input v-debounce:300ms="myFunc" />` however "myFunc" is never hit. I just have a simple `console.log("test") in there which never fires...

**Comment by ricky11** [comment]
how did you solve this?

**Comment by rpungello** [comment]
> how did you solve this?

I'd like to know as well, because I'm having the same issue.
https://xkcd.com/979/

**Comment by dhershman1** [comment]
You should be able to use the `getDirective` function introduced in v3 of the package if you want to only use the directive at a different level than global.

**Comment by ricky11** [comment]
How about in vue 2.x

**Comment by dhershman1** [comment]
v3 of vue debounce is backwards compatible to Vue 2 shouldn't be an issue

**Comment by rpungello** [comment]
> You should be able to use the `getDirective` function introduced in v3 of the package if you want to only use the directive at a different level than global.

I did that, but still have the same issue as OP originally did.

**Comment by dhershman1** [comment]
What does your usage look like.

**Comment by rpungello** [comment]
> What does your usage look like.

```
<template>
    <div>
        <input v-debounce="loadResults" type="text" name="test">
    </div>
</template>

<script>
    import { getDirective } from 'vue-debounce';

    export default {
        directives: {
            debounce: getDirective()
        },

        methods: {
            loadResults() {
                console.log('test'); // This never happens
            },
        },
    };
</script>

```

**Comment by dhershman1** [comment]
Hmm, it seems to be working fine for my tests, let me make a new environment and see if I can recreate it using single file components.

**Comment by dhershman1** [comment]
@rpungello I have it working here, if you don't mind could you work it to produce the same issue you're seeing and send it to me?
https://codesandbox.io/s/debounce-example-73g3q

If you're able to reproduce it please open a new issue with a link

**Comment by rpungello** [comment]
> @rpungello I have it working here, if you don't mind could you work it to produce the same issue you're seeing and send it to me?
> https://codesandbox.io/s/debounce-example-73g3q
> 
> If you're able to reproduce it please open a new issue with a link

According to `package.json`, that example is using Vue 2.6, but I'm using 3.0.
Is this just not compatible with Vue 3? That would explain my problem.

**Comment by dhershman1** [comment]
It should be compatible with Vue 3, you need to tell the getDirective function that because sadly I can't automatically get the version for you, you should do `getDirective(3)` and it should work for Vue 3.

I should probably make that clearer in the docs.

**Comment by rpungello** [comment]
> It should be compatible with Vue 3, you need to tell the getDirective function that because sadly I can't automatically get the version for you, you should do `getDirective(3)` and it should work for Vue 3.
> 
> I should probably make that clearer in the docs.

That did it, thank you!
Guess I should have read the docs more carefully, I was just copying the example code.

**Comment by dhershman1** [comment]
Awesome! I'll for sure update the readme to make that much clearer, I did a very poor job, thank you for your help!
