### ISSUE TITLE
Calling the debounce funtion unlimited times while page load if the input is not empty in Nuxt.js

### ISSUE THREAD

**Issue by kollolx** [dhershman1/vue-debounce#46]
```
 <input
   v-model="search_text"
   v-debounce:300ms="search()"
    type="text"
    placeholder="Search people"
 />
```

my plugin.js is
```
import vueDebounce from 'vue-debounce'

// Listening to multiple events
Vue.use(vueDebounce, {
  listenTo: ['input', 'keyup']
})

```

**Comment by dhershman1** [comment]
Well that's weird, It's been a hot minute since I've used Nuxt, could it be that nuxt keeps updating the input as the page loads in?

**Comment by kollolx** [comment]
is there any fix yet in nuxt?

**Comment by dhershman1** [comment]
I'm not able to reproduce this, can you show me what your search method looks like?

**Comment by kollolx** [comment]
Here is my search method looks like.
```
async search() {
    this.isLoading = true;
    const res = await this.callApi(
    "get",
    `some api`
    );

    if (res.status == 200) {
    this.allSearchResult = res.data.searchResult;

    } else {
        if (res.data.message) this.showErrorMessage(res.data.message);
    }
    this.isLoading = false;
}
```

**Comment by kollolx** [comment]
> I'm not able to reproduce this, can you show me what your `search` method looks like?
> 
> My guess might be that you're not returning a function in your search method so with the `()` at the end of search might be causing issue. Though I could also be 100% wrong! lol

It actually solves my issue

**Comment by ricky11** [comment]
if you need to pass a value in the function, then you would need the parentheses here in this case the event will fire and cause a loop.
