### ISSUE TITLE
Set default timeout other than 300ms?

### ISSUE THREAD

**Issue by georgyfarniev** [dhershman1/vue-debounce#5]
Hello. Thanks for this great module! Is it possible to implement setting of custom default timeout during install of this plugin (Vue.use(...)) ? Thanks

**Comment by dhershman1** [comment]
I can probably look into making this a part of the options.

**Comment by georgyfarniev** [comment]
@dhershman1 thank you. Let me know if PR is needed.

**Comment by dhershman1** [comment]
Created a PR #6 with this option. The new option/setting is called `defaultTime` Though the name can change if needed.

**Comment by dhershman1** [comment]
This is added and released on v1.3.0
