### ISSUE TITLE
vueDebounce doesn't work on safari browsers

### ISSUE THREAD

**Issue by nguyensyhung** [dhershman1/vue-debounce#51]
vueDebounce doesn't work on Safari browsers

**Comment by dhershman1** [comment]
I ran a few tests, I can't run my test html on safari because of js load issues. But once I brought in vue debounce from a non local location it seems to run fine on Safari.

Are you trying to run it locally? Which version of Safari?

**Comment by dhershman1** [comment]
I'm going to close this issue, if you need to please re open with a little more info if you can, thank you!
