### ISSUE TITLE
How to pass extra parameter to typing function

### ISSUE THREAD

**Issue by Nehasoni988** [dhershman1/vue-debounce#52]
`<input v-debounce:300ms="myFunc" type="text" />
`

How can I pass any extra parameter to myFunc?

@dhershman1

**Comment by dhershman1** [comment]
Simply make `myFunc` a closure like this:

```js
myFunc: (arg) => (arg2) => console.log(arg, arg2)
```

And then you can use vue debounce like this:

```
<input v-debounce:300ms="myFunc('hello')" type="text" /> 
```

**Comment by Nehasoni988** [comment]
Yeah, it worked, but how can I access Vue's other data properties inside this closure function because "this" is not accessible inside the closure.
could you please suggest?

@dhershman1

**Comment by dhershman1** [comment]
That's odd, if you use an arrow function it loses the scope on `this` ?

**Comment by Nehasoni988** [comment]
Yes, please see this example- https://codesandbox.io/s/pensive-babbage-0u2j9?file=/src/App.vue

@dhershman1

**Comment by dhershman1** [comment]
Wow, that's really weird. It looks like if you start with an arrow function vue loses its scope, so if you do this:

```
myFunc (arg1) {
  return (arg2) => this.printMe(arg1, arg2)
}
```

It should work as expected.

**Comment by dhershman1** [comment]
Hopefully this fixed your issue, if not please feel free to re open this issue.
