### ISSUE TITLE
Method not firing

### ISSUE THREAD

**Issue by ricky11** [dhershman1/vue-debounce#53]
`  <input type="text" v-model="searchQ" v-debounce:400ms="searchQs" debounce-events="keyup" placeholder="Search"/>
`
Above is my input element, and I have a corresponding method called searchQs.

When typing text in the input I am using keyup event listener, but it seems the function is not being fired?

Any ideas.

Thanks

**Comment by dhershman1** [comment]
Hey! I think you might've forgot to add in the code! Could you please throw that on there so I can get a better look? Thanks! 😄

**Comment by ricky11** [comment]
Added. thanks.

**Comment by ricky11** [comment]
When i move the component to main.js and call add the directive globally it works, but since i don't need it globally i would like to add it to a parent component, would i be able to do that.  

I also have a problem with sending empty strings, despite having cancelonempty

  <input type="text" v-model="searchQ" v-debounce:500ms.cancelonempty="searchQs" debounce-events="input" placeholder="Search emails, files or messages"/>


it seems that if a string has "     "   spaces it isn't considered empty?   but a string as "" is empty and wont fire.

how can i disable calling the function even if the string has many spaces in it and no other text?

**Comment by dhershman1** [comment]
I would have to add a tweak but technically speaking a space in a string makes it so the string is not empty, so it really depends on what we want to define as it being empty.

I can probably add in an option that you can set to true to trim strings, this should counter act that.

As for your original question, I am unsure of the parent component as I've always plugged my directives into to vue directly since vue runs install functions on build. I'll have to build a test case around that and experiment.

**Comment by ricky11** [comment]
Hi, Thank you.

Yes i would be good to 
1) ignore or trim all debounce functions that have a empty input  or a string with spaces only..  For example when in my text box when i press the space bar multiple times the event is fired. I could do a check in the function i guess.

2) The reason why i don't want to put v-debounce directive in the mian.js file is that i don't need this module globally (to reduce bundle size) i try to put all modules in components that need them.    I think i can do this with the directive: { } but not exactly sure how this works.

thanks.

**Comment by dhershman1** [comment]
I've created a PR #54 

This adds the new trim option, as well as adds a function you can use with the `directives` key on a component. It will return the directive back so you can assign it for use on components directly instead of globally.

**Comment by dhershman1** [comment]
v3 has been released to npm, you should be able to update your package.json to v3 and install it. If you run into any issues please let me know !
