### ISSUE TITLE
When I use debounce directly in the method, I have to add a parenthesis to make it work properly. why?

### ISSUE THREAD

**Issue by nekooee** [dhershman1/vue-debounce#60]
**Version of Vue**
Which version of vue are you using?
Vue 2
**Browser**
What browser are you using?
chrome
Type out the question to the best of your ability!

When I use debounce directly in the method, I have to add a parenthesis to make it work properly.

my method is:
```php
 feedCallback(opts, callback) {            

            debounce(() => {
                this.getUsers();
            }, 400)

  }
```
the above code does not call the getUsers() method.

But the following code works well with an extra parenthesis at the end of the debounce. Why?
```php
 feedCallback(opts, callback) {       
     
            debounce(() => {
                this.getUsers();
            }, 400)()

  }
```

**Comment by dhershman1** [comment]
`debounce` is a closure, so it returns a function when called, since the initialization is just the setup for your debounce, the following calls are what actually trigger that debounce action.
