### ISSUE TITLE
:debounce-events="['blur']" not overriding

### ISSUE THREAD

**Issue by TerryCaliendo-WealthCounsel** [dhershman1/vue-debounce#66]
Vue 2.6
Chrome (latest version)

The :debounce-events doesn't seem to override on Vuetify components.   Vuetify is a custom component and the docs seem to say the vue-debounce works with custom components.  

Here is a codesandbox showing the issue:
https://codesandbox.io/s/vue-debounce-with-vuetify-blur-issue-7bp8lh?file=/src/App.vue:307-334

You'll see that if you update the input by typing some text, the debounced function still fires after 1s even though the :debounce-events is set to "blur", not "input".  From the documentation, the debounce-events should override any other event types, correct?

**Comment by TerryCaliendo-WealthCounsel** [comment]
Thanks... I tried changing it to `onblur`.  That didn't help.  Tried changing it to `click` as well and it still fires as though the `:debounce-events` is not seen.

**Comment by dhershman1** [comment]
Hmmmm very interesting, I shall do some research

**Comment by TerryCaliendo-WealthCounsel** [comment]
Awesome.  Hope you find a solution!  Let me know if there's anything I can do to help research.  From what I've seen in forum posts, people are saying if you want to communicate between [Hook Functions](https://v2.vuejs.org/v2/guide/custom-directive.html#Hook-Functions); but we don't need to share a variable, we need to share a function.

Other things I'm seeing is that if you want access to lifecycle events, you need a component.   So I'm trying to fathom how to create a debouncer component.  I've got an idea for something with scoped-slots, but its ugly and I'm hoping you can come up with solution using the directive you've created!

**Comment by dhershman1** [comment]
Sorry this took me so long, but I've been super busy with work. So upon testing with Vuetify, It seems like it doesn't actually give me access to the attributes. I'm not sure why, but I'll keep digging to try and figure that out.

**Comment by TerryCaliendo-WealthCounsel** [comment]
Thanks... I'd think you are trying to catch the bubbling of the event, so even if its super-nested, you should still get the bubble of the event... unless Vuetify is stopping/preventing the bubble?

**Comment by dhershman1** [comment]
The problem is, Vuetify puts the "debounce-events" attribute on the `input` but gives vue-debounce the very top div, so it isn't telling me the events you want to look for, weirdly enough. If it applied the attributes to the top level div like it does the directive then it would probably work without a hitch.

**Comment by KaelWD** [comment]
You have access to attributes through the vnode argument: https://codepen.io/kaelwd/pen/abVrvMK?editors=1010

**Comment by TerryCaliendo-WealthCounsel** [comment]
I'm a bit lost here so I'm not sure if this is helpful... but [focusout](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusout_event) bubbles from the input (unlike `blurr`)

**Comment by dhershman1** [comment]
It looks like with the new code I have in place `focusout` is indeed captured and triggers the handler thanks to its bubbling. The other thing could also be that I think vuetify applies its own blur events and what not.

**Comment by dhershman1** [comment]
Super late, I got swamped with a bunch of work suddenly.

I released the new vnode flow to make debounce work with stuff liek vuetify much better. I still need to figure out a better way for when events are already listening and overwriting debounce.

This is a good step forward though.

**Comment by TerryCaliendo-WealthCounsel** [comment]
Thanks.  Have you given any thought to this discussion: https://github.com/dhershman1/vue-debounce/discussions/68

I could really use a way to force fire the debouncer when the component unmounts (per the discussion above)
