### ISSUE TITLE
v5.0.0 Migration Warning

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/vue-debounce#76]
Hello! I am writing this issue to hopefully warn everyone using this package that I think I'm going to split it up into 2 packages.

I really really **really** hate the way the code works between Vue 2 and Vue 3, so I think I'm going to dedicate vue-debounce to Vue3, and then I'll make a new package with which name I shall list here at a later date when this project starts.

Thank you for the support and downloading of this silly little tool!

You can now start migrating to the new package here: [vue2-debounce](https://github.com/dhershman1/vue2-debounce)

Edit: It's finally here! #85

**Comment by MartinX3** [comment]
Is this the same for vue 2.7?
It should backport some compatibility from vue 3

**Comment by dhershman1** [comment]
This package is still backward compatible as of right now, I haven't made any clear jump to starting the conversion as I just haven't had the free time. 

The idea here is because of the way Vue2 handles plugins or directives like this package is a little bit different than how vue 3 does it. Mostly verbiage and how the install functionality works. Right now vue-debounce has a whole bunch of overhead to try and get you the right version of the directive you need to use for your instance of vue.

I don't like this because it relies on strings, and manually getting the version from the user, kind of stinky. Hence the main reason I want to break up the package

**Comment by MartinX3** [comment]
That would be nice.
Vue 2.6 is end of life. (2.7 will be on 2023-12-31).

https://v2.vuejs.org/v2/guide/migration-vue-2-7.html

**Comment by dhershman1** [comment]
It looks like with my very light digging, that vue 2.7 still uses the same verbiage as the rest of vue2, which does line up. So I don't think vue-debounce would support 2.7 but vue2-debounce (linked above) will continue to support it after v5 of this package releases (You can also choose to just use the current version of vue-debounce for the foreseeable future if needed, but it wouldn't receive patches or chore updates like vue2-debounce would)

Hopefully that makes sense, if its gibberish please feel free to ask anymore questions and I will do my best to answer or look into them! :D

**Comment by dhershman1** [comment]
v5.0.0 has released
