### ISSUE TITLE
Should use addEventListener instead of overriding native callback

### ISSUE THREAD

**Issue by thejcannon** [dhershman1/vue-debounce#8]
Overriding the native callbacks can lead to unexpected bugs from client code, especially in a rich ecosystem where we can inspect the listeners.

Don't know the difficulty of appending to `$listeners` but knowing Vue, it'll probably "just work"

(Additionally, using the native events makes libraries like `vue-test-utils`, which uses `$listeners`, not play nicely with `vue-debounce`)

**Comment by dhershman1** [comment]
Hey thanks for using the package! That's a good idea and I will for sure be looking into that.

**Comment by thejcannon** [comment]
I poked around a bit to see if I couldn't come up with some test code to give to you as a starting point but everything I've tried so far has failed. 

Most notably adding the `vnode` argument to `bind` and then calling `vnode.componentInstance.$on('keyup', (...){...})` seems to have no effect on the component's listeners. (Immediately printing `vnode.componentInstance.$listeners` doesn't show any change).

Adding the listener directly also doesn't seem to change anything.

I'm interested to see if you have any luck. (Either way I think this still demonstrates a hole in the event handling logic of `vue-test-utils`.)

**Comment by dhershman1** [comment]
Hmm, I see. Do you mind sharing your findings anyway? To give a basic foundation to take examples from?

**Comment by thejcannon** [comment]
Yeah, that's probably the best medium. It's unfortunate that on the surface Vue events and native events seem to "just work" as one thing (Vue listeners). But the deeper you go, that breaks down.

So this issue I suppose is just "don't override the event" add it to the list of listeners. I'll change the title.

**Comment by dhershman1** [comment]
Added breaking label since this will need to change how events are given to the package. So this should be a v2.0.0 feature

**Comment by dhershman1** [comment]
PR Opened.

**Comment by dhershman1** [comment]
PR Merged and v2.0.0 released onto npm
