### ISSUE TITLE
How to use with <script setup> syntax?

### ISSUE THREAD

**Issue by nikriaz** [dhershman1/vue-debounce#80]
**Version of Vue**
3.3.4

If I import custom directive locally to the component, its name under <script setup> syntax should follow specific naming convention:
https://vuejs.org/api/sfc-script-setup.html#using-custom-directives

This is how I'm trying to use it (other part of code omitted for brevity):

```
 <input name="inputSearch"
                   v-model="inputSearch"
                   v-debounce="test"/>
                   
<script setup lang="ts">
import { vue3Debounce } from 'vue-debounce'

    const vDebounce = {
        debounce: vue3Debounce({ fireOnEmpty: true })
    }; 
    
     const test = async () => {
        console.log(inputSearch.value);
        const searchResult = await searchApi( inputSearch.value);
    };
```
Nothing happens, just `test `isn't called on input. No errors. It works if I use traditional export default syntax.

Also, to be honest I would prefer to use debounce as a function in the script part of SFC and keep html standard rather setting custom directives, Maybe there is a such option?

**Comment by dhershman1** [comment]
Hello Sorry this got buried in my notifications, you can use debounce by itself!

The function is available to be imported, you can see the example on the readme!

As for the setup question I'll need to do some research on why that isn't working properly. Thank you for the report!

**Comment by dhershman1** [comment]
The readme now reflects how to use this with the setup syntax (Finally)
